// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_interfaces.go -package=mocks -source=interfaces.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	application "coworking/internal/booking/application"
	outbox "coworking/internal/booking/application/outbox"
	domain "coworking/internal/booking/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
	isgomock struct{}
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// ConfirmPayment mocks base method.
func (m *MockBookingService) ConfirmPayment(ctx context.Context, input application.ConfirmPaymentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPayment", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPayment indicates an expected call of ConfirmPayment.
func (mr *MockBookingServiceMockRecorder) ConfirmPayment(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPayment", reflect.TypeOf((*MockBookingService)(nil).ConfirmPayment), ctx, input)
}

// CreateBooking mocks base method.
func (m *MockBookingService) CreateBooking(ctx context.Context, input application.CreateBookingInput) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, input)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingServiceMockRecorder) CreateBooking(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingService)(nil).CreateBooking), ctx, input)
}

// GetBooking mocks base method.
func (m *MockBookingService) GetBooking(ctx context.Context, id uuid.UUID) (*application.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooking", ctx, id)
	ret0, _ := ret[0].(*application.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooking indicates an expected call of GetBooking.
func (mr *MockBookingServiceMockRecorder) GetBooking(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooking", reflect.TypeOf((*MockBookingService)(nil).GetBooking), ctx, id)
}

// MockBookingRepo is a mock of BookingRepo interface.
type MockBookingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepoMockRecorder
	isgomock struct{}
}

// MockBookingRepoMockRecorder is the mock recorder for MockBookingRepo.
type MockBookingRepoMockRecorder struct {
	mock *MockBookingRepo
}

// NewMockBookingRepo creates a new mock instance.
func NewMockBookingRepo(ctrl *gomock.Controller) *MockBookingRepo {
	mock := &MockBookingRepo{ctrl: ctrl}
	mock.recorder = &MockBookingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepo) EXPECT() *MockBookingRepoMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockBookingRepo) FindByID(ctx context.Context, id uuid.UUID) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBookingRepoMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBookingRepo)(nil).FindByID), ctx, id)
}

// FindByIdempotencyKey mocks base method.
func (m *MockBookingRepo) FindByIdempotencyKey(ctx context.Context, key string) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdempotencyKey indicates an expected call of FindByIdempotencyKey.
func (mr *MockBookingRepoMockRecorder) FindByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdempotencyKey", reflect.TypeOf((*MockBookingRepo)(nil).FindByIdempotencyKey), ctx, key)
}

// Save mocks base method.
func (m *MockBookingRepo) Save(ctx context.Context, b *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockBookingRepoMockRecorder) Save(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBookingRepo)(nil).Save), ctx, b)
}

// MockPaymentGateway is a mock of PaymentGateway interface.
type MockPaymentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentGatewayMockRecorder
	isgomock struct{}
}

// MockPaymentGatewayMockRecorder is the mock recorder for MockPaymentGateway.
type MockPaymentGatewayMockRecorder struct {
	mock *MockPaymentGateway
}

// NewMockPaymentGateway creates a new mock instance.
func NewMockPaymentGateway(ctrl *gomock.Controller) *MockPaymentGateway {
	mock := &MockPaymentGateway{ctrl: ctrl}
	mock.recorder = &MockPaymentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentGateway) EXPECT() *MockPaymentGatewayMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockPaymentGateway) Charge(ctx context.Context, bookingID string, amount decimal.Decimal, currency string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, bookingID, amount, currency)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Charge indicates an expected call of Charge.
func (mr *MockPaymentGatewayMockRecorder) Charge(ctx, bookingID, amount, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockPaymentGateway)(nil).Charge), ctx, bookingID, amount, currency)
}

// MockAvailabilityChecker is a mock of AvailabilityChecker interface.
type MockAvailabilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockAvailabilityCheckerMockRecorder
	isgomock struct{}
}

// MockAvailabilityCheckerMockRecorder is the mock recorder for MockAvailabilityChecker.
type MockAvailabilityCheckerMockRecorder struct {
	mock *MockAvailabilityChecker
}

// NewMockAvailabilityChecker creates a new mock instance.
func NewMockAvailabilityChecker(ctrl *gomock.Controller) *MockAvailabilityChecker {
	mock := &MockAvailabilityChecker{ctrl: ctrl}
	mock.recorder = &MockAvailabilityCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailabilityChecker) EXPECT() *MockAvailabilityCheckerMockRecorder {
	return m.recorder
}

// CheckAvailability mocks base method.
func (m *MockAvailabilityChecker) CheckAvailability(ctx context.Context, roomID uuid.UUID, slot domain.DateRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailability", ctx, roomID, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailability indicates an expected call of CheckAvailability.
func (mr *MockAvailabilityCheckerMockRecorder) CheckAvailability(ctx, roomID, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailability", reflect.TypeOf((*MockAvailabilityChecker)(nil).CheckAvailability), ctx, roomID, slot)
}

// MockPriceCalculator is a mock of PriceCalculator interface.
type MockPriceCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockPriceCalculatorMockRecorder
	isgomock struct{}
}

// MockPriceCalculatorMockRecorder is the mock recorder for MockPriceCalculator.
type MockPriceCalculatorMockRecorder struct {
	mock *MockPriceCalculator
}

// NewMockPriceCalculator creates a new mock instance.
func NewMockPriceCalculator(ctrl *gomock.Controller) *MockPriceCalculator {
	mock := &MockPriceCalculator{ctrl: ctrl}
	mock.recorder = &MockPriceCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceCalculator) EXPECT() *MockPriceCalculatorMockRecorder {
	return m.recorder
}

// CalculatePrice mocks base method.
func (m *MockPriceCalculator) CalculatePrice(ctx context.Context, roomID uuid.UUID, slot domain.DateRange) (domain.Money, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculatePrice", ctx, roomID, slot)
	ret0, _ := ret[0].(domain.Money)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculatePrice indicates an expected call of CalculatePrice.
func (mr *MockPriceCalculatorMockRecorder) CalculatePrice(ctx, roomID, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculatePrice", reflect.TypeOf((*MockPriceCalculator)(nil).CalculatePrice), ctx, roomID, slot)
}

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUnitOfWork) Execute(ctx context.Context, fn func(application.BookingRepo, application.EventStore) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUnitOfWorkMockRecorder) Execute(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUnitOfWork)(nil).Execute), ctx, fn)
}

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// SaveEvents mocks base method.
func (m *MockEventStore) SaveEvents(ctx context.Context, events []domain.EventItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvents indicates an expected call of SaveEvents.
func (mr *MockEventStoreMockRecorder) SaveEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvents", reflect.TypeOf((*MockEventStore)(nil).SaveEvents), ctx, events)
}

// MockEventsRepo is a mock of EventsRepo interface.
type MockEventsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventsRepoMockRecorder
	isgomock struct{}
}

// MockEventsRepoMockRecorder is the mock recorder for MockEventsRepo.
type MockEventsRepoMockRecorder struct {
	mock *MockEventsRepo
}

// NewMockEventsRepo creates a new mock instance.
func NewMockEventsRepo(ctrl *gomock.Controller) *MockEventsRepo {
	mock := &MockEventsRepo{ctrl: ctrl}
	mock.recorder = &MockEventsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsRepo) EXPECT() *MockEventsRepoMockRecorder {
	return m.recorder
}

// MarkDoneEvents mocks base method.
func (m *MockEventsRepo) MarkDoneEvents(ctx context.Context, events []outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDoneEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDoneEvents indicates an expected call of MarkDoneEvents.
func (mr *MockEventsRepoMockRecorder) MarkDoneEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDoneEvents", reflect.TypeOf((*MockEventsRepo)(nil).MarkDoneEvents), ctx, events)
}

// PullNewEvents mocks base method.
func (m *MockEventsRepo) PullNewEvents(ctx context.Context, batchSize, reserveTTLSec int) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullNewEvents", ctx, batchSize, reserveTTLSec)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullNewEvents indicates an expected call of PullNewEvents.
func (mr *MockEventsRepoMockRecorder) PullNewEvents(ctx, batchSize, reserveTTLSec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullNewEvents", reflect.TypeOf((*MockEventsRepo)(nil).PullNewEvents), ctx, batchSize, reserveTTLSec)
}

// SaveEvents mocks base method.
func (m *MockEventsRepo) SaveEvents(ctx context.Context, events []domain.EventItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvents indicates an expected call of SaveEvents.
func (mr *MockEventsRepoMockRecorder) SaveEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvents", reflect.TypeOf((*MockEventsRepo)(nil).SaveEvents), ctx, events)
}
